/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119502-g12b853530a-20250515"
#endif /* AVUTIL_FFVERSION_H */
